### ISSUE TITLE
Unexpected text

### ISSUE THREAD

**Issue by Ekwav** [Coflnet/TabFlutter#4]
Why does this display `hi` for the column in the selected element?  
That is rather confusing 
![Image](https://github.com/user-attachments/assets/286eb4d4-9416-4c08-b070-455a84667142)

Also the Jay here is nothing that got entered. I would expect it to state what type the column is. Also the e in `Hello` should be lower case.
![Image](https://github.com/user-attachments/assets/7795e771-1b47-4254-9851-9abf398f4ce1)

**Comment by tentamens** [comment]
"Also the Jay here is nothing that got entered. I would expect it to state what type the column is"
I don't think I am understanding this "Jay" probably just a hallucination. But the way you interact with the column depicts what type it is, If it is a number you can only input numbers, list ext.

**Comment by Ekwav** [comment]
> "Also the Jay here is nothing that got entered. I would expect it to state what type the column is"
> I don't think I am understanding this "Jay" probably just a hallucination. But the way you interact with the column depicts what type it is, If it is a number you can only input numbers, list ext. 


I don't understand. Why is there, hallucinated, text for an entry on the settings page?
![Screenshot_2024-09-28-12-49-17-80_b16efc086b1a51ac356648170be53388.jpg](https://github.com/user-attachments/assets/e9020cce-fc5b-4ece-bb8b-c349a937615b)

**Comment by tentamens** [comment]
I think I resolved that, when ever you would make a change in recent log it would also affect the the selected log
